### ISSUE TITLE
Перенести "Alarm! СложнА-А-А!" в README.md

### ISSUE THREAD

**Issue by dani32iz** [iatudev/html-agnecy#10]
Для инструкций обычно используется файл README.md, который пишется в формате markdown.

Необходимо перенести txt инструкцию в README и удалить текстовый файл
"html-agnecy/Alarm! СложнА-А-А! Что делать.txt"

**Comment by dani32iz** [comment]
@degorychev вижу что ты активен, можешь задачу сделать, заодно дополнишь инструкцию

**Comment by Desten73** [comment]
Да-да-да, секунду. Мы тут с Денисом просто обсуждали это все дело.

**Comment by Desten73** [comment]
@dani32iz Да-да-да, секунду, сейчас все сделаю. Мы тут с Денисом просто обсуждали это все дело.

**Comment by 1mmense** [comment]
Я вроде поковырялся с ридми и txt-шником, теперь всё должно выглядеть, как надо

**Comment by 1mmense** [comment]
А ещё я когда-нибудь научусь @ использовать

**Comment by Desten73** [comment]
@1mmense кажется можно закрывать задачку.
