### ISSUE TITLE
Почистить код, отступы в едином стиле

### ISSUE THREAD

**Issue by dani32iz** [iatudev/html-agnecy#12]
![image](https://user-images.githubusercontent.com/4288245/30823187-6c5281a2-a23c-11e7-8f9f-a70f093389b8.png)

**Comment by degorychev** [comment]
![image](https://user-images.githubusercontent.com/32064103/30824094-76ba04dc-a23f-11e7-84e3-3c4cfe95901f.png)
@dani32iz  В Notepad++ Проблем нет

**Comment by dani32iz** [comment]
Проверь символ отступа, везде должны быть 4 пробела
