### ISSUE TITLE
Часть 2. Feature products

### ISSUE THREAD

**Issue by Desten73** [iatudev/html-agnecy#15]
![1](https://user-images.githubusercontent.com/32061906/30844824-ce6e8326-a2a1-11e7-9868-ca5d7313afff.png)

**Comment by Desten73** [comment]
Полосочку сверху тоже нарисовать.

**Comment by Desten73** [comment]
Можете попилить на верх(надписи) и низ(картинки). Первый создает ветку и берет верх, второй дорабатывает в этой же ветке низ. Затем соединяете с мастером.

**Comment by 1mmense** [comment]
@Desten73 Что конкретно нужно сделать? А то "берёт верх/низ" - не очень информативно

**Comment by Desten73** [comment]
@1mmense  Один до картинок, второй остальное

**Comment by 1mmense** [comment]
@Desten73 Информативненько

**Comment by degorychev** [comment]
@Desten73 @1mmense Эта "полосочка" скорее всего рисуется тегом `<hr>`, естественно с измененным стилем, так к слову...

**Comment by Desten73** [comment]
@1mmense Я не понимаю, что тебе тут нужно описать.
https://app.zeplin.io/project/59c10dc3b5260d38e02d9810/screen/59c111015e818b41132a1e6a
